"""
AI Storyboard Pro - Setup Wizard

Interactive configuration wizard for first-time setup.
Guides users through setting up API keys and other configuration.
"""

import os
import sys
import shutil
from pathlib import Path
from typing import Optional, Tuple


def get_input(prompt: str, default: str = "") -> str:
    """Get user input with optional default value."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "

    try:
        value = input(prompt).strip()
        return value if value else default
    except (EOFError, KeyboardInterrupt):
        print("\n\nSetup cancelled.")
        sys.exit(1)


def get_yes_no(prompt: str, default: bool = True) -> bool:
    """Get yes/no input from user."""
    default_str = "Y/n" if default else "y/N"
    try:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not response:
            return default
        return response in ("y", "yes", "1", "true")
    except (EOFError, KeyboardInterrupt):
        print("\n\nSetup cancelled.")
        sys.exit(1)


def validate_api_key(api_key: str) -> Tuple[bool, str]:
    """
    Validate API key format.

    Returns:
        Tuple of (is_valid, error_message)
    """
    if not api_key:
        return False, "API key cannot be empty"

    if api_key == "your_api_key_here":
        return False, "Please enter your actual API key"

    # Basic format check (adjust based on actual key format)
    if len(api_key) < 10:
        return False, "API key seems too short"

    return True, ""


def validate_port(port_str: str) -> Tuple[bool, int, str]:
    """
    Validate port number.

    Returns:
        Tuple of (is_valid, port_number, error_message)
    """
    try:
        port = int(port_str)
        if 1 <= port <= 65535:
            return True, port, ""
        return False, 0, "Port must be between 1 and 65535"
    except ValueError:
        return False, 0, "Port must be a number"


def create_env_file(config: dict) -> str:
    """Create .env file from configuration dictionary."""
    base_dir = Path(__file__).parent
    env_path = base_dir / ".env"

    lines = [
        "# AI Storyboard Pro Configuration",
        "# Generated by setup wizard",
        "",
        "# API Configuration",
        f"NANA_BANANA_API_KEY={config['api_key']}",
        f"NANA_BANANA_BASE_URL={config.get('api_base_url', 'https://api.nanabanana.pro')}",
        "",
        "# Server Configuration",
        f"GRADIO_PORT={config.get('gradio_port', 7861)}",
        f"API_PORT={config.get('api_port', 8000)}",
        "",
        "# CORS Configuration",
        f"CORS_ORIGINS={config.get('cors_origins', '*')}",
        "",
        "# File Upload Configuration",
        f"MAX_UPLOAD_SIZE_MB={config.get('max_upload_size_mb', 50)}",
        "",
        "# Debug Mode",
        f"DEBUG={str(config.get('debug', False)).lower()}",
        "",
    ]

    # Optional ComfyUI config
    if config.get('comfyui_host'):
        lines.extend([
            "# ComfyUI Integration",
            f"COMFYUI_HOST={config['comfyui_host']}",
            f"COMFYUI_PORT={config.get('comfyui_port', 8188)}",
            "",
        ])

    # Optional Ollama config
    if config.get('ollama_host'):
        lines.extend([
            "# Ollama Integration",
            f"OLLAMA_HOST={config['ollama_host']}",
            f"OLLAMA_PORT={config.get('ollama_port', 11434)}",
            "",
        ])

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return str(env_path)


def run_wizard(force: bool = False) -> bool:
    """
    Run the interactive setup wizard.

    Args:
        force: If True, run even if .env already exists

    Returns:
        True if setup completed successfully
    """
    base_dir = Path(__file__).parent
    env_path = base_dir / ".env"
    env_example_path = base_dir / ".env.example"

    print()
    print("=" * 50)
    print("  AI Storyboard Pro - Setup Wizard")
    print("=" * 50)
    print()

    # Check if .env already exists
    if env_path.exists() and not force:
        print("Configuration file (.env) already exists.")

        # Try to load and validate existing config
        try:
            from settings import settings, reload_settings
            reload_settings()

            errors = settings.validate()
            if errors:
                print("\nCurrent configuration has issues:")
                for error in errors:
                    print(f"  - {error}")
                print()

                if not get_yes_no("Would you like to reconfigure?"):
                    return False
            else:
                print("Current configuration appears valid.")
                if not get_yes_no("Would you like to reconfigure anyway?", default=False):
                    return True
        except ImportError:
            pass

    print()
    print("This wizard will help you configure AI Storyboard Pro.")
    print("Press Ctrl+C at any time to cancel.")
    print()

    config = {}

    # ===========================================
    # API Configuration
    # ===========================================
    print("-" * 40)
    print("API Configuration")
    print("-" * 40)
    print()
    print("You need an API key from the image generation service.")
    print("Get your API key from: https://nanabanana.pro")
    print()

    while True:
        api_key = get_input("Enter your API key")
        valid, error = validate_api_key(api_key)
        if valid:
            config['api_key'] = api_key
            break
        print(f"  Error: {error}")
        print()

    config['api_base_url'] = get_input(
        "API base URL",
        "https://api.nanabanana.pro"
    )
    print()

    # ===========================================
    # Server Configuration
    # ===========================================
    print("-" * 40)
    print("Server Configuration")
    print("-" * 40)
    print()

    while True:
        port_str = get_input("Gradio UI port", "7861")
        valid, port, error = validate_port(port_str)
        if valid:
            config['gradio_port'] = port
            break
        print(f"  Error: {error}")

    while True:
        port_str = get_input("API server port", "8000")
        valid, port, error = validate_port(port_str)
        if valid:
            config['api_port'] = port
            break
        print(f"  Error: {error}")
    print()

    # ===========================================
    # CORS Configuration
    # ===========================================
    print("-" * 40)
    print("CORS Configuration")
    print("-" * 40)
    print()
    print("CORS controls which domains can access your API.")
    print("Use '*' for development, or specify domains for production.")
    print("Example: http://localhost:3000,https://myapp.com")
    print()

    config['cors_origins'] = get_input("Allowed origins", "*")
    print()

    # ===========================================
    # Optional: ComfyUI
    # ===========================================
    print("-" * 40)
    print("Optional: ComfyUI Integration")
    print("-" * 40)
    print()

    if get_yes_no("Do you want to configure ComfyUI integration?", default=False):
        config['comfyui_host'] = get_input("ComfyUI host", "127.0.0.1")
        while True:
            port_str = get_input("ComfyUI port", "8188")
            valid, port, error = validate_port(port_str)
            if valid:
                config['comfyui_port'] = port
                break
            print(f"  Error: {error}")
    print()

    # ===========================================
    # Optional: Ollama
    # ===========================================
    print("-" * 40)
    print("Optional: Ollama Integration")
    print("-" * 40)
    print()

    if get_yes_no("Do you want to configure Ollama for local AI?", default=False):
        config['ollama_host'] = get_input("Ollama host", "localhost")
        while True:
            port_str = get_input("Ollama port", "11434")
            valid, port, error = validate_port(port_str)
            if valid:
                config['ollama_port'] = port
                break
            print(f"  Error: {error}")
    print()

    # ===========================================
    # Debug Mode
    # ===========================================
    config['debug'] = get_yes_no("Enable debug mode?", default=False)
    print()

    # ===========================================
    # Summary and Confirmation
    # ===========================================
    print("=" * 50)
    print("Configuration Summary")
    print("=" * 50)
    print()

    api_key_display = "***" + config['api_key'][-8:] if len(config['api_key']) > 8 else "***"
    print(f"API Key: {api_key_display}")
    print(f"API URL: {config['api_base_url']}")
    print(f"Gradio Port: {config['gradio_port']}")
    print(f"API Port: {config['api_port']}")
    print(f"CORS Origins: {config['cors_origins']}")

    if config.get('comfyui_host'):
        print(f"ComfyUI: {config['comfyui_host']}:{config['comfyui_port']}")
    if config.get('ollama_host'):
        print(f"Ollama: {config['ollama_host']}:{config['ollama_port']}")

    print(f"Debug Mode: {config['debug']}")
    print()

    if not get_yes_no("Save this configuration?"):
        print("\nSetup cancelled. No changes made.")
        return False

    # ===========================================
    # Save Configuration
    # ===========================================
    try:
        env_file = create_env_file(config)
        print()
        print("=" * 50)
        print("  Setup Complete!")
        print("=" * 50)
        print()
        print(f"Configuration saved to: {env_file}")
        print()
        print("You can now start the application:")
        print("  - Windows: start.bat or start_api.bat")
        print("  - Linux/Mac: ./start.sh or ./start_api.sh")
        print()
        return True
    except Exception as e:
        print(f"\nError saving configuration: {e}")
        return False


def verify_config() -> Tuple[bool, list]:
    """
    Verify current configuration is valid.

    Returns:
        Tuple of (is_valid, list_of_errors)
    """
    try:
        from settings import settings, reload_settings
        reload_settings()
        errors = settings.validate()
        return len(errors) == 0, errors
    except Exception as e:
        return False, [str(e)]


def print_current_config():
    """Print current configuration status."""
    try:
        from settings import settings, reload_settings
        reload_settings()
        settings.print_config()
    except Exception as e:
        print(f"Error loading configuration: {e}")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="AI Storyboard Pro Setup Wizard")
    parser.add_argument(
        "--force", "-f",
        action="store_true",
        help="Force reconfiguration even if .env exists"
    )
    parser.add_argument(
        "--verify", "-v",
        action="store_true",
        help="Verify current configuration"
    )
    parser.add_argument(
        "--show", "-s",
        action="store_true",
        help="Show current configuration"
    )

    args = parser.parse_args()

    if args.verify:
        valid, errors = verify_config()
        if valid:
            print("Configuration is valid.")
            sys.exit(0)
        else:
            print("Configuration errors:")
            for error in errors:
                print(f"  - {error}")
            sys.exit(1)
    elif args.show:
        print_current_config()
    else:
        success = run_wizard(force=args.force)
        sys.exit(0 if success else 1)
